/* This file was auto-generated by 'gentables.py'. Do not edit manually. */

#include "Test_ConeProjection_tbl0.cpp"
#include "Test_ConeProjection_tbl1.cpp"
#include "Test_ConeProjection_tbl2.cpp"

const unsigned int Test_ConeProjection::nconespec = 3;
const struct conemodel_spec *Test_ConeProjection::conespec[Test_ConeProjection::nconespec] = {
    Test_ConeProjection_conespec0,
    Test_ConeProjection_conespec1,
    Test_ConeProjection_conespec2
};
const unsigned int Test_ConeProjection::conespec_N[Test_ConeProjection::nconespec] = {
    Test_ConeProjection_nconespec0,
    Test_ConeProjection_nconespec1,
    Test_ConeProjection_nconespec2
};
const slibreal_t *Test_ConeProjection::detdir[Test_ConeProjection::nconespec] = {
    Test_ConeProjection_detdir0,
    Test_ConeProjection_detdir1,
    Test_ConeProjection_detdir2
};
const slibreal_t *Test_ConeProjection::detpos[Test_ConeProjection::nconespec] = {
    Test_ConeProjection_detpos0,
    Test_ConeProjection_detpos1,
    Test_ConeProjection_detpos2
};
const slibreal_t Test_ConeProjection::visang[Test_ConeProjection::nconespec] = {
    Test_ConeProjection_visang0,
    Test_ConeProjection_visang1,
    Test_ConeProjection_visang2
};
const slibreal_t Test_ConeProjection::aperture[Test_ConeProjection::nconespec] = {
    Test_ConeProjection_aperture0,
    Test_ConeProjection_aperture1,
    Test_ConeProjection_aperture2
};
